### ISSUE TITLE
Sample repo showcase with config for vitest/jest/mocha

### ISSUE THREAD

**Issue by capaj** [rezonant/typescript-rtti#11]
I see you have some custom solution for running tests.
For me the biggest barrier to start using this in production right now is being able to use rtti in popular testing frameworks.
My usual ones are jest and vitest. Mocha would be nice to have too. 
Having a sample repo with a showcase how to configure this would be amazing.

I might dabble with this myself, not sure if I will achieve anything soon, so if anyone has this set up, please let me know.

**Comment by rezonant** [comment]
Good idea! For jest, here's a quick sample: https://github.com/rezonant/typescript-rtti-jest

Make sure to use `typescript-rtti@0.1.2` or later, as I found an issue that caused ts-jest's own transformers to fail (through no fault of their own!)

I don't use jest myself, I use [razmin](https://github.com/rezonant/razmin) [which I wrote], as it tracks all async operations automatically and requires no setup. You simply compile your tests with your application using `tsc` (or, in this case, `ttsc`) and then run `node dist/test`. You can then prune your tests out of your package / deliverable by excluding `src/**/*.test.ts` and `dist/**/*.test.js`. Uses a jasmine/mocha/jest testing style (describe/it) and supports any assertion library you want (or just throw exceptions). 

I thought jest also tracked async operations but I guess not: 
![image](https://user-images.githubusercontent.com/409140/154247101-0709024d-d120-45c4-adff-b34c528fda57.png)

Anyway, this jest sample is just for simple Node.js tests, not running in the browser or anything fancy. Would love if others could make up sample repos, or just let me know if they run into any trouble with more complicated test setups.

**Comment by rezonant** [comment]
The "custom" bits in typescript-rtti's test suite is the "corpus" tests, which check out specific git tags from GitHub, rewrite the codebase's build step to use ttsc, build the library using the typescript-rtti transformer and then run the codebase's test suite to ensure the transformer does not break any code during transformation.

**Comment by capaj** [comment]
I have tried to add rtti to my jest specs here:

```
    TypeError: Cannot read properties of null (reading 'kind')

      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:87213:25)
      at visitor (node_modules/ts-jest/dist/transformers/hoist-jest.js:72:33)
      at visitNode (node_modules/typescript/lib/typescript.js:87005:23)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:87400:378)
      at visitor (node_modules/ts-jest/dist/transformers/hoist-jest.js:72:33)
      at visitNode (node_modules/typescript/lib/typescript.js:87005:23)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:87632:115)
      at visitor (node_modules/ts-jest/dist/transformers/hoist-jest.js:72:33)
      at visitNodes (node_modules/typescript/lib/typescript.js:87058:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:87364:68)
```

and almost all of my tests get this type error :point_up: 

You can run this on your machine if you want, just checkout, install and `yarn test`: https://github.com/capaj/decapi/tree/rtti-wip

**Comment by rezonant** [comment]
Looks like the same error I encountered and fixed but it looks like you are already using 0.1.2 (the fixed version). Guess there are other places were passing null instead of undefined. I'll take a look this evening

**Comment by rezonant** [comment]
OK, looks like I missed a spot. v0.1.3 is out now with that fix. With that fix, the rtti-wip branch doesn't fail during transformation, but the tests do fail. I *think* this is just the state of the code but let me know if you think the transformer is doing something wrong.

Also, I've added decapi 1.0.0 to the corpus test (let me know if you're not OK with that) and it is passing your test suite with the transformer in place, so I'm guessing the test failures on master/rtti-wip are just related to the changes you're working on.

**Comment by capaj** [comment]
@rezonant whoa that was crazy fast!
Thanks so much. Jest now runs nicely.
It is an honor for me to provide decapi codebase as a test case for this repo! It means I can rely on it without the fear of subtle breaking changes in any release.

The fact that the specs fail is due to the reliance on the regular typescript reflection, which is replaced I guess.
I will close this issue as we do have jest sample repo now and for mocha I am sure I can figure it out. For vitest it will be a bit trickier as it relies on esbuild, but it should be doable with a custom vite TS plugin.

**Comment by capaj** [comment]
oh yeah looking at one of the failed tests in the decapi codebase( https://github.com/capaj/decapi/blob/4acc440f0463b61d6b819a49a0c751f2208fec32/src/domains/field/Field.spec.ts#L275), I am calling:
```ts
Reflect.getMetadata('design:returntype', target, key)
```
and in regular TS I get back a function which:
```ts
    const stringSignature = inferedType.toString()
    console.log('~ stringSignature', stringSignature) // ~ stringSignature function Function() { [native code] }

```

but it should output:
```
~ stringSignature function Promise() { [native code] }
```

**Comment by rezonant** [comment]
This is quite a thorough library! Made a lot of progress tonight on the test suite, but there are still more cases to cover tomorrow.

**Comment by capaj** [comment]
:1st_place_medal:  no rush. Decapi is currently only used by a single product in production and it's in maintenance mode now.

**Comment by rezonant** [comment]
On a side note:

So this is my first serious work time with Jest and I have to say- it is a real pain in the butt.

- Stack trace filenames are shortened making navigation from within VS code difficult
- Stack traces themselves are shortened to the point of being pretty much meaningless, including not linking to the test file itself, meaning you have to search the codebase for the describe/it text instead of just jumping to the test

Here's a screenshot of what I mean:
![image](https://user-images.githubusercontent.com/409140/154589328-f7147e1a-8294-4008-8840-02f7963a7007.png)

On top of that, since Jest has it's own transformers and interacts with Typescript in a nonstandard way *and* doesn't write it's output to disk in a way I can inspect, it makes this particular process much more difficult. This is more about ts-jest as well than jest, but ts-jest does appear to be the standard way to run Typescript: It creates a brand new transformer for every file (even in the same process) instead of creating a single ts.Program. 

Also while trying to debug an issue last night, I added `tsconfig: "tsconfig.json"`-- if you do that it won't find it for various pathing reasons and will instead silently revert to the standard Typescript settings which include having emitDecoratorMetadata turned off, but yet also experimentalDecorators turned _on_ (?!?) even though that's not a default. 

Jest is slow (infinitely slow?) in CI unless you add the three magical `--dont-suck-in-ci` parameters, Jest transformers cannot be easily debugged due to it's multi-process nature *but* they can be debugged just fine if you limit your test suite to a single file which is a bit of unnecessary magic. 

Also `it.only()` only affects the file its in, not the entire test suite which means you either have to use the command line filtering (which also inexplicably doesn't support Windows path styles despite Node.js supporting them) or modify the jest.config filter to limit the tests you want to run in a single cycle. 

It's output is unnecessarily complex and wordy, adding 5-6 lines for each test failure that just shows the code, I think this provides little value.

I haven't tried vitest, and of course I've used mocha, but the way people talk about Jest like it's a revolutionary test framework makes me scratch my head. When in multiprocess mode it runs roughly the same amount of tests in the same amount of time as a linear test runner, but also loses the ability to track the relationship between trace messages, printed errors, and the tests being run and indeed sometimes fully eats console.logs without ever printing them even in test failure... And tracing was an important tool for me last night since debugging transformers (and even code under test itself) is nowhere near as straightforward and reliable as it is when you just run your tests in a single node process like Mocha or razmin do.

@capaj I would recommend you move to something else for your own sanity, but I'm curious what benefits you see for it over just using traditional test runners like jasmine/mocha/razmin.

**Comment by capaj** [comment]
I fully agree regarding jest. It's bloated and very hacky. 
I am using vitest for most of my new repos these days.
Tap and mocha are the next candidates.
I will try to setup rtti with one of these 3 next. Ideally I'd like to move to vitest in decapi, if it can work well with rtti.

**Comment by rezonant** [comment]
Phew glad I'm not the only one haha. We may debate about GraphQL but jest.... eh....

Anyway yeah given the fact I've needed to make several lateral (ie not bug fixes, just work arounds for jest quirks) changes to typescript-rtti to ensure jest doesn't explode, I'm realizing that putting some attention on how it works in vitest would be prudent as from what I gather it is also not a simple runner

**Comment by rezonant** [comment]
OK, _now_ its good. The 1.0.0 release of decapi fully passes its test suite under typescript-rtti@0.1.4

**Comment by capaj** [comment]
Hmm have you commited all the changes? I am seeing 
```
 5 failed, 1 skipped, 1 todo, 113 passed, 120 total
```

Mostly these errors:

```
 ● Fields based on getters › Will work with getter field

    @ObjectType Foo.bar: Could not infer return type and no type is explicitly configured. In case of circular dependencies make sure to explicitly set a type.

      53 |   const inferedType = inferTypeByTarget(target.prototype, fieldName)
      54 |   if (!inferedType) {
    > 55 |     throw new FieldError(
         |           ^
      56 |       target,
      57 |       fieldName,
      58 |       `Could not infer return type and no type is explicitly configured. In case of circular dependencies make sure to explicitly set a type.`

      at inferTypeOrThrow (src/domains/field/compiler/fieldType.ts:55:11)
      at resolveRegisteredOrInferredType (src/domains/field/compiler/services.ts:24:10)
      at compileFieldConfig (src/domains/field/compiler/fieldCompiler.ts:41:24)
      at Object.keys.forEach.__RtΦ.n (src/domains/field/compiler/fieldCompiler.ts:88:35)
          at Array.forEach (<anonymous>)
      at getAllFields (src/domains/field/compiler/fieldCompiler.ts:77:23)
      at targetWithParents.forEach.__RtΦ.n (src/domains/field/compiler/fieldCompiler.ts:97:35)
          at Array.forEach (<anonymous>)
      at compileAllFields (src/domains/field/compiler/fieldCompiler.ts:96:21)
      at src/domains/objectType/compiler/objectType.ts:52:12

```

**Comment by rezonant** [comment]
Did you upgrade to 0.1.4 ? If I pull rtti-wip branch, and upgrade to typescript-rtti 0.1.4 and run the suite it does seem to pass, no?
![image](https://user-images.githubusercontent.com/409140/154794312-e9f33726-d210-4f22-a9b1-bc6e937b9ebb.png)

**Comment by capaj** [comment]
not for me, I did update to `0.1.4` as you can see here:
![image](https://user-images.githubusercontent.com/1305378/154797329-7a76a4d1-3d4b-4eae-aaec-98933f08a0a7.png)

My node.js version is 16.14.0 but that should not make a difference.

**Comment by capaj** [comment]
Oh it was jest cache :facepalm: 

I cleared it and it runs now.
I do still get these:
```
RangeError: Maximum call stack size exceeded
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:3:26)
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:24:61)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:827:49)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:60
    at Array.map (<anonymous>)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:39)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:830:91
    at Array.map (<anonymous>)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:830:70)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:60
RTTI: Failed to build source file /home/capaj/oss/graphql-repos/typegql/src/domains/union/compileUnionType.ts: Maximum call stack size exceeded [please report]
RangeError: Maximum call stack size exceeded
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:3:26)
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:24:61)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:827:49)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:60
    at Array.map (<anonymous>)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:39)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:830:91
    at Array.map (<anonymous>)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:830:70)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:60
RTTI: Failed while processing node 'return (value, context, info) => {
    const rawResolvedType = originalResolver(value, context, info)
    return resolveType(rawResolvedType)
  }' in /home/capaj/oss/graphql-repos/typegql/src/domains/union/compileUnionType.ts:
RangeError: Maximum call stack size exceeded
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:3:26)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:10:72
    at Array.map (<anonymous>)
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:10:63)
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:24:61)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:827:49)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:60
    at Array.map (<anonymous>)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:39)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:830:91
RTTI: Failed while processing node '{
  return (value, context, info) => {
    const rawResolvedType = originalResolver(value, context, info)
    return resolveType(rawResolvedType)
  }
}' in /home/capaj/oss/graphql-repos/typegql/src/domains/union/compileUnionType.ts:
RangeError: Maximum call stack size exceeded
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:3:26)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:10:72
    at Array.map (<anonymous>)
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:10:63)
    at serialize (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/serialize.ts:24:61)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:827:49)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:60
    at Array.map (<anonymous>)
    at typeToTypeRef (/home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:809:39)
    at /home/capaj/oss/graphql-repos/typegql/node_modules/typescript-rtti/src/transformer/index.ts:830:91

```

Which looks bad, but otherwise :heavy_check_mark:

**Comment by rezonant** [comment]
Hmm perhaps I missed these, will check. Opened #15 to track
