### ISSUE TITLE
Why is null showing up as Boolean?

### ISSUE THREAD

**Issue by capaj** [rezonant/typescript-rtti#5]
I have this code:
```ts
import 'reflect-metadata'
import { ReflectedClass } from 'typescript-rtti'

class A {
  constructor(readonly someValue: Number, private someOtherValue: string) {}
}

class A2 {}

class B {
  private foo: A
  bar = 123
  async baz(): Promise<Array<A | null>> {
    return [this.foo]
  }
}

let bClass = new ReflectedClass(B)
// @ts-expect-error


console.log(bClass.getMethod('baz').returnType._ref.p[0].p[0])
```

And the output is:
```
{ 'TΦ': '|', t: [ [Function: A], [Function: Boolean] ] }
```

I would expect something like 
```
{ 'TΦ': '|', t: [ [Function: A], null ] }
```

**Comment by rezonant** [comment]
Additionally I think these should be emitting forward references (ie `() => A` and `() => null`)

**Comment by rezonant** [comment]
The issue is that Type Literals were not handled, so it fell through to the Type Predicate handling (which defaults to returning `Boolean`). Type Predicate would be, for instance `foo is Bar`.

**Comment by rezonant** [comment]
Released in v0.0.18

**Comment by rezonant** [comment]
Also turns out we are not missing the forward reference, it's been awhile since I've had my head in the RTTI game :-)

It is forward referenced _at the top_ to ensure resolution works all down the line:

```typescript
__RtΦ("rt:t", () => ({ TΦ: "|", t: [String, Number] }))
           // ^---- right there :-D
```

**Comment by capaj** [comment]
works flawlessly in the 0.0.19. Thank you!
